### ISSUE TITLE
Project Maintaining

### ISSUE THREAD

**Issue by gustawdaniel** [ilyapt/facebook-nologin-scraper#5]
Hi @ilyapt  

I see that project is not updatef for 4 yeras. I am creating commercial project that uses your package as component. My company can maintain this repository.

Your url will be left and in all places we will mention about you are creator, but we will accept pull request like added by @mihailShumilov.

It can be done like on

https://github.com/graphql-nexus/nexus

Code-First Type-Safe GraphQL Framework
Maintained with hearts by Precise Lab • Facebook Nologin Scraper originally by Ilyapt

This proposition is because of great pull request is not accepted. I am goin to add my own and improve your open source software.

What I propose to introduce:

- https://github.com/ilyapt/facebook-nologin-scraper/pull/6 - automated testing
- https://github.com/ilyapt/facebook-nologin-scraper/pull/7 - fixed vulnerabilities

**Comment by gustawdaniel** [comment]
https://github.com/ilyapt/facebook-nologin-scraper/pull/6

**Comment by ilyapt** [comment]
Hi Daniel,

Thank you for your message, your right, unfortunately I don't have enough time and I abandoned this project. But os couse if people need it, project should be supported. I sent you invite to projects collaborators

**Comment by gustawdaniel** [comment]
Thank you @ilyapt.

My proposed roadmap:

- rewrite project to typescript
- split project to more files
- add normalization of fb links to remove trace from mobile vs www
- add documentation about usage with proxy
- replace request by axios
- add automatic test in jest
- connect with travis

You are author of this project and if you want discuss any point of this roadmap please give me feedback.

**Comment by ilyapt** [comment]
@gustawdaniel 

Your roadmap looks strong and right. I totally agree with you.

**Comment by gustawdaniel** [comment]
Done.
